version: "3.8"

services:
  db:
    image: postgres:15
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 3s
      retries: 20

  odoo:
    image: odoo:18.0
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8069:8069"
    env_file: .env
    environment:
      - HOST=db
      - USER=${POSTGRES_USER}
      - PASSWORD=${POSTGRES_PASSWORD}
      - ADMIN_PASS=${ODOO_ADMIN_PASS}
    volumes:
      - ./addons:/mnt/extra-addons
      - odoo-data:/var/lib/odoo
    command: >
      odoo -d ${POSTGRES_DB}
           --dev=reload
           --addons-path=/usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons

volumes:
  pgdata:
  odoo-data:
